AdventureAtlas/Models/ErrorViewModel.cs
namespace AdventureAtlas.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AdventureAtlas/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace AdventureAtlas.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

AdventureAtlas/Controllers/HomeController.cs
using AdventureAtlas.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AdventureAtlas.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AdventureAtlas/Controllers/TravelGuidesController.cs
using Microsoft.AspNetCore.Mvc;

namespace AdventureAtlas.Controllers
{
    public class TravelGuidesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

AdventureAtlas/Views/About/Index.cshtml
@{
    ViewData["Title"] = "About";
}

<body>
    <div class="containerabout">
        <div class="column column-image">
            <img src="~/img/montanha.jpg" alt="Imagem de montanha">
        </div>
        <div class="column column-text">
            <p><span class="greeting">Olá, viajantes!</span> Meu nome é Hemily e sou uma exploradora ávida, apaixonada por descobrir os cantos mais remotos e fascinantes do mundo. Desde criança, o desejo de viajar e experimentar novas culturas está gravado em meu coração.</p>
            <p>O Adventure Atlas nasceu de uma profunda necessidade de compartilhar minhas experiências de viagem e inspirar outros a explorar o mundo ao seu redor. Após inúmeras aventuras em lugares exóticos e encantadores, percebi que cada viagem é uma oportunidade não apenas de explorar novos lugares, mas também de aprender, crescer e se conectar com pessoas e culturas diversas.</p>
            <p>Decidi iniciar este blog como uma plataforma para relatar minhas jornadas, desde as pitorescas vilas europeias até as majestosas montanhas da Ásia e os vibrantes mercados da América Latina. Acredito que cada destino tem uma história única para contar e estou determinada a compartilhar essas histórias com o mundo.</p>
            <p>O objetivo do Adventure Atlas é oferecer aos leitores uma fonte de inspiração para suas próprias aventuras. Quero fornecer dicas práticas, recomendações sinceras e relatos honestos de minhas experiências para ajudar os viajantes a planejar e desfrutar de viagens memoráveis. Além disso, estou empenhada em promover o turismo responsável e sustentável, respeitando e preservando os destinos que tanto amamos explorar.</p>
            <p>Se você compartilha minha paixão pela aventura, então você veio ao lugar certo. Bem-vindo ao Adventure Atlas - onde a jornada é tão emocionante quanto o destino!</p>
        </div>
    </div>
</body>

AdventureAtlas/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "HOME";
}

    <div class="containerhome">
        <header>
            <h1 class="main-title">VIAJE DE MANEIRA MAIS INTELIGENTE, MAIS BARATA E POR MAIS TEMPO</h1>
            <p class="sub-title">Onde você quer ir?</p>
            <img class="img" src="~/img/viagens.jpg" />
        </header>
    </div>

AdventureAtlas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title style="font-weight:bold;font-family:Arial, sans-serif">@ViewData["Title"] - AdventureAtlas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AdventureAtlas.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AdventureAtlas</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">HOME</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TravelGuides" asp-action="Index">TRAVEL GUIDES</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="About" asp-action="Index">ABOUT US</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AdventureAtlas
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AdventureAtlas/Views/TravelGuides/Index.cshtml
@{
    ViewData["Title"] = "TravelGuides";
}
    <body>
        <p class="section section-content">Meus guias de viagem têm como objetivo fornecer as melhores e mais atualizadas informações sobre os principais destinos de viagem ao redor do mundo. (Eu sei como é ruim obter informações desatualizadas de um guia impresso, por isso mantenho todas essas páginas atualizadas constantemente!) Aqui você encontrará coisas para ver e fazer, informações sobre custos, meus melhores conselhos para economizar dinheiro, recomendações de lugares para ficar, sugestões de restaurantes, dicas de transporte e conselhos de segurança.</p>
    <h1 class="main-titlee" style="margin-bottom:2%">GUIA DE VIAGEM DA TAILÂNDIA</h1>
        <img class="img" src="~/img/thailandguide.jpg" />
        <h2 class="sub-title" style="margin-top:2%">OS TRÊS PRINCIPAIS LUGARES PARA SE VISITAR</h2>
        <ol>
            <li class="section">
                <h3 class="section-title">Visite Banguecoque</h3>
                <p class="section-content">Bangkok é uma cidade caótica e imperdível. Aqui você pode explorar templos, palácios reais, mercados incríveis, uma das cenas noturnas mais loucas do mundo e, claro, comer toda a incrível comida tailandesa. Confira Khao San Road para ver o refúgio dos mochileiros, Thong Lor/Ekamai para a vida noturna tailandesa local, veja as belas obras de arte do Grande Palácio e o Buda esmeralda e faça compras no Chatuchak Weekend Market. Bangkok é uma cebola que precisa de tempo para ser descascada. Saia da rota turística, coma nos mercados, explore a vida noturna e simplesmente relaxe.</p>
            </li>
            <li class="section">
                <h3 class="section-title">Aventura em Chiang Mai</h3>
                <p class="section-content">Chiang Mai é uma cidade repleta de templos, mercados de comida incríveis, mercados noturnos, muitos cafés e um clima descontraído. É uma boa plataforma de lançamento para passeios de vários dias na selva, atividades de aventura ou visitas aos santuários de elefantes próximos, onde você pode se voluntariar para ajudar os elefantes resgatados. E não deixe de ir ao Wat Doi Suthep, o templo mais famoso de Chiang Mai (o pagode supostamente contém relíquias do próprio Buda). Chiang Mai também é considerada uma das capitais gastronômicas do país, então não deixe de se fartar de comida. Também há uma grande cena de jazz aqui!</p>
            </li>
            <li class="section">
                <h3 class="section-title">Caminhada no Parque Nacional Khao Yai</h3>
                <p class="section-content">O Parque Nacional Khao Yai, localizado a cerca de 2,5 horas ao norte de Bangkok, é um dos melhores parques nacionais da Tailândia. É visualmente deslumbrante, repleto de flora e fauna exuberantes, muitas cachoeiras, trilhas para caminhadas e até alguns elefantes selvagens. É um lugar de visita obrigatória. Fique na Greenleaf Guesthouse para obter as melhores ofertas de passeios/acomodações na região.</p>
            </li>
        </ol>
    </body>